const BASE={
a_navAbout:'About GKB',a_navWhy:'Why GKB',a_navPartnership:'Academy Partnership',a_navPilot:'4-Week Pilot',a_navFaq:'FAQ',a_navMeeting:'Discuss Partnership',
a_heroTag:'Overseas Academy Partnership',a_hero1:'Prepare Your Students',a_hero2:'for Real Life in Korea.',a_hero3:'Partner with GKB.',a_heroDesc:'GKB helps overseas Korean academies prepare students not only for Korean language, but also for real life in Korea, workplace communication, cultural understanding, and trusted human experience.',a_heroBtn1:'See Partnership Model',a_heroBtn2:'See 4-Week Pilot',a_heroNote:'Learners connect through the academy. GKB does not replace local education; it adds practical preparation for life in Korea.',
a_cardTitle:'Your academy’s strength + GKB’s Korea-side experience',a_cardDesc:'We divide roles clearly and use 1:1 Zoom as the standard online format.',a_academyShort:'OVERSEAS ACADEMY',a_academyShortDesc:'Learner connection · basic learning management · local language support',a_gkbShortDesc:'Real Korea content · class support · experience connection',a_stat1:'First Pilot',a_stat2:'Zoom Standard',a_stat3:'First Meeting',
a_f1Title:'Korean used beyond textbooks',a_f1Desc:'Connect practical daily and workplace expressions to your academy classes.',a_f2Title:'Prepare for real life in Korea',a_f2Desc:'Help students understand transport, healthcare, housing, workplace culture and daily systems before arrival.',a_f3Title:'Experience from people who came first',a_f3Desc:'Bring real stories from Migrant Partners with life experience in Korea into learning.',
a_whyTitle:'Your academy already teaches Korean. GKB connects what comes next.',a_whyDesc:'Preparing for a Korean test and preparing to live in Korea are not the same. GKB respects your academy’s education and helps fill the practical gap.',a_whyHtml:"<article class='reason'><div class='num'>1</div><h3>We do not replace your academy</h3><p>We build on your curriculum and learner relationships and add only what is needed.</p></article><article class='reason'><div class='num'>2</div><h3>We start small and test together</h3><p>We use a 4-week pilot, with 1:1 Zoom as the standard online format, to check learner response and effectiveness.</p></article><article class='reason'><div class='num'>3</div><h3>We connect real Korean experience</h3><p>We bring daily life, workplace, culture and lived human experience into the learning process.</p></article>",
a_rolesTitle:'Clear roles create a strong partnership.',a_rolesDesc:'The academy connects and manages learners. GKB provides Korea-based content, teaching support and lived experience for the academy’s students.',a_academyRoleTag:'Academy Role',a_academyRoleTitle:'The local education partner closest to students',a_academyRoles:'<li>Connect suitable learners and check basic level</li><li>Manage classroom or online access</li><li>Attendance and basic learning management</li><li>Local-language support</li><li>Collect learner feedback</li>',a_gkbRoleTag:'GKB Role',a_gkbRoleTitle:'Korea-side education support partner',a_gkbRoles:'<li>4-week pilot curriculum</li><li>1:1 Zoom-based online class support</li><li>Real Korea life and workplace content</li><li>Migrant Partner experience connection</li><li>Teacher/operator feedback meeting and improvement report</li>',a_roleNote:'Important: GKB does not recruit the academy’s learners directly. The academy connects suitable learners after coordination. For online Zoom lessons, GKB uses 1:1 as the standard; group or hybrid formats are discussed separately.',
a_pilotTitle:'Start the first collaboration with a clear 4-week pilot.',a_pilotDesc:'Begin with 1:1 Zoom as the standard online format, review the outcome together, then decide the next step. Group or hybrid classes can be discussed separately with the academy.',a_pilotFacts:"<div class='fact'><b>4 weeks</b><span>First collaboration</span></div><div class='fact'><b>1:1</b><span>Zoom standard</span></div><div class='fact'><b>Group / Hybrid</b><span>Discussed separately</span></div><div class='fact'><b>Joint Review</b><span>Review after completion</span></div>",a_pilotFocus:'Basic Korean + Korean life + practical workplace/daily expressions + experience from people who have lived in Korea',
a_processTitle:'Coordinate with the academy first, then meet the learner.',a_processDesc:'We do not recruit students first. We listen to the institution’s needs, co-design the pilot, and then the academy connects a suitable learner. Zoom begins with 1:1 as the standard.',a_processHtml:"<article class='process-step'><div class='no'>1</div><h3>30-minute online meeting</h3><p>We first listen to the academy and learner situation.</p></article><article class='process-step'><div class='no'>2</div><h3>Co-design the pilot</h3><p>Agree on level, time, format and roles.</p></article><article class='process-step'><div class='no'>3</div><h3>Academy connects learner</h3><p>For Zoom, GKB begins with 1:1 as the standard. Group formats are coordinated separately.</p></article><article class='process-step'><div class='no'>4</div><h3>4-week pilot</h3><p>Combine GKB content with academy support.</p></article><article class='process-step'><div class='no'>5</div><h3>Joint evaluation</h3><p>Review feedback and results, then decide the next step.</p></article>",
a_networkTitle:'GKB’s difference is connection with people who have already lived in Korea.',a_networkDesc:'Migrant Partners are GKB’s Korea-side support network sharing real life and communication experience with academy learners.',a_networkCardTitle:'Answer the practical questions learners really have.',a_networkCardDesc:'Experiences that are difficult to explain through textbooks alone are shared in the language of people who lived them.',a_networkHtml:'<li>Challenges faced at work for the first time</li><li>Important points when communicating with Koreans</li><li>Useful things to know about transport, healthcare and daily life</li><li>What they wish they had known before arriving in Korea</li>',
a_principlesTitle:'Start small, agree clearly, improve together.',a_principlesDesc:'Partnership is built around learner education and trust.',a_valuesHtml:"<div class='value'><b>Respect</b><span>Respect academy and learners</span></div><div class='value'><b>Clarity</b><span>Clear roles and commitments</span></div><div class='value'><b>Privacy</b><span>Protect personal data</span></div><div class='value'><b>Feedback</b><span>Joint review and improvement</span></div><div class='value'><b>Trust</b><span>Long-term trust</span></div>",a_notice:'GKB does not guarantee jobs, visas or EPS results as an educational product, and does not present itself as a government or public program. Before any formal partnership or payment agreement, local legal, tax and education requirements should be reviewed together.',
a_faqTitle:'What overseas academies usually ask first',a_faqDesc:'We explain the basic structure clearly before discussing cooperation.',a_faqHtml:'<details><summary>Who connects the learners?</summary><p>The academy does. GKB does not recruit learners directly from this website. We support learners connected through an agreed academy.</p></details><details><summary>What is the standard class size for Zoom?</summary><p>GKB’s basic Zoom model is 1:1. Group classes or classroom-plus-online hybrid formats can be discussed separately with the academy.</p></details><details><summary>Do we need to change our existing classes?</summary><p>No. We respect your current classes and add agreed Korea-life and workplace-communication content where useful.</p></details><details><summary>Does GKB guarantee jobs or visas?</summary><p>No. GKB does not guarantee or broker jobs, visas or EPS results.</p></details><details><summary>How are costs decided?</summary><p>After reviewing class time, delivery format and local conditions, the contracting parties separately agree on cost and payment.</p></details><details><summary>How do we begin?</summary><p>We start with a 30-minute online meeting to understand your learners, levels, needs and online environment, then co-design a suitable pilot.</p></details>',
a_meetingTitle:'Start with a 30-minute conversation, not a big contract.',a_meetingDesc:'Reply to the person who shared this page with you. We would first like to understand your academy and learners, then explore whether a suitable 4-week 1:1 Zoom pilot makes sense.',a_meetingBtn1:'Review Partnership Roles',a_meetingBtn2:'Review 4-Week Pilot',a_agendaHtml:'<div><b>5 min</b><span>Academy introduction</span></div><div><b>10 min</b><span>Learner and needs</span></div><div><b>10 min</b><span>4-week 1:1 pilot</span></div><div><b>5 min</b><span>Agree next step</span></div>',a_footer:'Overseas Academy Partnership · Korea-side Human Network'};

const KO={
a_navAbout:'GKB 소개',a_navWhy:'Why GKB',a_navPartnership:'학원 협력',a_navPilot:'4주 Pilot',a_navFaq:'FAQ',a_navMeeting:'파트너십 논의',
a_heroTag:'Overseas Academy Partnership',a_hero1:'학생들의 한국 준비를',a_hero2:'실제 삶까지 연결하세요.',a_hero3:'GKB와 함께하십시오.',a_heroDesc:'GKB는 해외 한국어학원이 학생들에게 한국어뿐 아니라 실제 한국생활, 직장 소통, 문화 이해와 사람의 경험까지 준비시킬 수 있도록 돕는 교육 파트너입니다.',a_heroBtn1:'협력 모델 보기',a_heroBtn2:'4주 Pilot 보기',a_heroNote:'학습자는 학원을 통해 연결됩니다. GKB는 현지 학원의 교육을 대체하지 않고, 실제 한국생활 준비를 더합니다.',
a_cardTitle:'현지 학원의 강점 + GKB의 한국 현장 경험',a_cardDesc:'역할을 분명히 나누고 온라인은 Zoom 1:1을 기본으로 시작합니다.',a_academyShort:'OVERSEAS ACADEMY',a_academyShortDesc:'학습자 연결 · 기본 학습관리 · 현지 언어 지원',a_gkbShortDesc:'실제 한국생활 콘텐츠 · 수업지원 · 경험 연결',a_stat1:'첫 Pilot',a_stat2:'Zoom 기본',a_stat3:'첫 미팅',
a_f1Title:'교재 밖에서 쓰는 한국어',a_f1Desc:'일상과 직장에서 실제로 필요한 표현을 학원 수업과 연결합니다.',a_f2Title:'한국생활을 미리 이해',a_f2Desc:'교통, 병원, 주거, 직장문화 등 학생들이 한국에서 만나게 될 현실을 준비합니다.',a_f3Title:'먼저 살아본 사람의 경험',a_f3Desc:'한국생활 경험을 가진 Migrant Partner의 실제 이야기를 교육에 연결합니다.',
a_whyTitle:'학원은 이미 한국어를 가르칩니다. GKB는 그 다음을 연결합니다.',a_whyDesc:'학생이 한국어 시험을 준비하는 것과 한국에서 실제로 살아가는 것은 같은 일이 아닙니다. GKB는 기존 학원의 교육을 존중하면서 한국생활 준비라는 빈틈을 함께 채웁니다.',a_whyHtml:"<article class='reason'><div class='num'>1</div><h3>학원 교육을 대체하지 않습니다</h3><p>현지 학원의 커리큘럼과 관계를 기반으로 필요한 부분만 더합니다.</p></article><article class='reason'><div class='num'>2</div><h3>Zoom은 1:1을 기본으로 합니다</h3><p>4주 Pilot에서 학습자 한 사람에게 집중해 반응과 효과를 세밀하게 확인합니다.</p></article><article class='reason'><div class='num'>3</div><h3>한국의 실제 경험을 연결합니다</h3><p>언어 뒤에 있는 생활, 직장, 문화, 사람의 경험을 교육 콘텐츠로 제공합니다.</p></article>",
a_rolesTitle:'역할이 명확해야 좋은 파트너십이 됩니다.',a_rolesDesc:'학습자는 해외학원이 연결하고 관리합니다. GKB는 학원의 학생에게 필요한 한국 현장 기반 콘텐츠와 수업지원, 사람의 경험을 제공합니다.',a_academyRoleTag:'해외학원 역할',a_academyRoleTitle:'학생과 가장 가까운 현지 교육 파트너',a_academyRoles:'<li>적합한 학습자 연결 및 기본 수준 확인</li><li>수업 장소 또는 온라인 접속 관리</li><li>출석과 기본 학습관리</li><li>현지 언어 지원</li><li>학습자 피드백 수집</li>',a_gkbRoleTag:'GKB 역할',a_gkbRoleTitle:'한국 현장과 연결되는 교육 지원 파트너',a_gkbRoles:'<li>4주 Pilot 커리큘럼</li><li>Zoom 1:1 기반 온라인 수업지원</li><li>실제 한국생활·직장 상황 콘텐츠</li><li>Migrant Partner 경험 연결</li><li>교사·운영자 피드백 회의와 개선 리포트</li>',a_roleNote:'중요: GKB가 해외학원의 학생을 직접 모집하는 구조가 아닙니다. 학원과 협의한 뒤 학원이 적합한 학습자를 연결합니다. 온라인 Zoom 수업은 1:1을 기본 원칙으로 하며, 그룹수업이나 혼합형은 별도 협의합니다.',
a_pilotTitle:'첫 협력은 4주 Pilot으로 가볍고 명확하게 시작합니다.',a_pilotDesc:'온라인은 Zoom 1:1을 기본으로 실제 수업을 진행하고 결과를 함께 확인한 뒤 다음 협력을 결정합니다. 그룹수업이나 혼합형은 학원과 별도 협의합니다.',a_pilotFacts:"<div class='fact'><b>4주</b><span>첫 협력 기간</span></div><div class='fact'><b>1:1</b><span>Zoom 기본 원칙</span></div><div class='fact'><b>그룹 / 혼합</b><span>학원과 별도 협의</span></div><div class='fact'><b>공동 리뷰</b><span>종료 후 결과 검토</span></div>",a_pilotFocus:'한국어 기초 + 한국생활 + 직장·생활 실제 표현 + 한국에서 먼저 살아본 사람의 경험',
a_processTitle:'학원과 먼저 조율하고, 그 다음 학습자와 만납니다.',a_processDesc:'학생을 먼저 모집하지 않습니다. 기관의 필요와 환경을 듣고 Pilot을 함께 설계한 뒤 학원이 적합한 학습자를 연결합니다. Zoom은 1:1을 기본으로 시작합니다.',a_processHtml:"<article class='process-step'><div class='no'>1</div><h3>30분 온라인 미팅</h3><p>학원과 학습자 상황을 먼저 듣습니다.</p></article><article class='process-step'><div class='no'>2</div><h3>Pilot 공동 설계</h3><p>수준, 시간, 방식, 역할을 합의합니다.</p></article><article class='process-step'><div class='no'>3</div><h3>학원이 학습자 연결</h3><p>Zoom은 1:1을 기본으로 적합한 학습자를 연결합니다. 그룹형은 별도 협의합니다.</p></article><article class='process-step'><div class='no'>4</div><h3>4주 Pilot</h3><p>GKB 콘텐츠와 학원의 지원을 결합합니다.</p></article><article class='process-step'><div class='no'>5</div><h3>공동 평가</h3><p>피드백과 결과를 보고 다음 단계를 결정합니다.</p></article>",
a_networkTitle:'GKB의 차이는 ‘한국을 먼저 살아본 사람’과 연결된다는 점입니다.',a_networkDesc:'Migrant Partner는 해외학원 학생에게 한국의 실제 생활과 소통 경험을 전해 주는 GKB의 한국-side 지원 네트워크입니다.',a_networkCardTitle:'학생이 궁금해하는 현실적인 질문에 답합니다.',a_networkCardDesc:'교재만으로 설명하기 어려운 한국생활의 실제 모습을 경험자의 언어로 전달합니다.',a_networkHtml:'<li>직장에서 처음 겪었던 어려움</li><li>한국 사람과 소통할 때 중요한 점</li><li>교통·병원·생활에서 알아두면 좋은 것</li><li>처음 한국에 왔을 때 알았으면 좋았을 것</li>',
a_principlesTitle:'작게 시작하고, 명확하게 약속하고, 함께 개선합니다.',a_principlesDesc:'파트너십은 학생의 교육과 신뢰를 중심에 두고 운영합니다.',a_valuesHtml:"<div class='value'><b>Respect</b><span>학원과 학습자 존중</span></div><div class='value'><b>Clarity</b><span>역할과 약속 명확화</span></div><div class='value'><b>Privacy</b><span>개인정보 보호</span></div><div class='value'><b>Feedback</b><span>공동 평가와 개선</span></div><div class='value'><b>Trust</b><span>장기적인 신뢰</span></div>",a_notice:'GKB는 취업·비자·EPS 합격을 교육상품처럼 보장하지 않으며, 공공기관 또는 정부 프로그램으로 오인될 수 있는 표현을 사용하지 않습니다. 실제 제휴와 비용 협의 전에는 현지 법률·세무·교육 관련 요건을 함께 확인합니다.',
a_faqTitle:'해외학원이 가장 먼저 궁금해할 질문',a_faqDesc:'협력을 논의하기 전에 기본 구조를 분명히 설명합니다.',a_faqHtml:'<details><summary>학습자는 누가 연결합니까?</summary><p>학원이 연결합니다. GKB는 홈페이지에서 학습자를 직접 모집하지 않고, 협의된 학원을 통해 연결된 학습자를 지원합니다.</p></details><details><summary>Zoom 수업은 몇 명이 기본입니까?</summary><p>원칙적으로 1:1입니다. 그룹수업이나 현지 교실+온라인 혼합형은 학원 상황에 맞춰 별도 협의합니다.</p></details><details><summary>학원 수업을 바꿔야 합니까?</summary><p>아닙니다. 기존 학원의 수업을 존중하며, 필요한 한국생활·직장소통 콘텐츠를 협의해 추가합니다.</p></details><details><summary>GKB가 취업이나 비자를 보장합니까?</summary><p>아닙니다. GKB는 취업, 비자, EPS 결과를 보장하거나 대행하지 않습니다.</p></details><details><summary>비용은 어떻게 정합니까?</summary><p>수업시간, 운영방식, 현지 여건을 확인한 뒤 계약 당사자와 비용·지급방식을 별도로 합의합니다.</p></details><details><summary>협력을 어떻게 시작합니까?</summary><p>30분 온라인 미팅에서 학원의 현재 학습자, 수준, 필요, 온라인 환경을 먼저 듣고 적합한 Pilot을 함께 설계합니다.</p></details>',
a_meetingTitle:'큰 계약보다, 30분 대화에서 시작하겠습니다.',a_meetingDesc:'이 페이지를 보내드린 사람에게 회신해 주세요. 귀 학원의 학습자와 필요를 먼저 듣고, Zoom 1:1을 기본으로 하는 4주 Pilot이 적합한지 함께 살펴보겠습니다.',a_meetingBtn1:'협력 역할 다시 보기',a_meetingBtn2:'4주 Pilot 다시 보기',a_agendaHtml:'<div><b>5분</b><span>기관 소개</span></div><div><b>10분</b><span>학습자와 필요 파악</span></div><div><b>10분</b><span>4주 1:1 Pilot</span></div><div><b>5분</b><span>다음 단계 합의</span></div>',a_footer:'Overseas Academy Partnership · Korea-side Human Network'};

const SIMPLE={
vi:{a_navAbout:'Giới thiệu GKB',a_navPartnership:'Hợp tác học viện',a_navPilot:'Pilot 4 tuần',a_navMeeting:'Trao đổi hợp tác',a_heroTag:'Hợp tác Học viện Nước ngoài',a_hero1:'Chuẩn bị cho học viên',a_hero2:'cuộc sống thực tế tại Hàn Quốc.',a_hero3:'Hợp tác cùng GKB.',a_stat2:'Zoom 1:1',a_pilotDesc:'Hình thức trực tuyến tiêu chuẩn là Zoom 1:1. Lớp nhóm hoặc hybrid sẽ được trao đổi riêng với học viện.'},
ne:{a_navAbout:'GKB बारे',a_navPartnership:'एकेडेमी साझेदारी',a_navPilot:'४ हप्ता Pilot',a_navMeeting:'साझेदारी छलफल',a_heroTag:'विदेशी एकेडेमी साझेदारी',a_hero1:'तपाईंका विद्यार्थीलाई तयार गर्नुहोस्',a_hero2:'कोरियाको वास्तविक जीवनका लागि।',a_hero3:'GKB सँग साझेदारी गर्नुहोस्।',a_stat2:'Zoom 1:1',a_pilotDesc:'अनलाइन Zoom कक्षाको आधारभूत मोडेल 1:1 हो। समूह वा हाइब्रिड ढाँचा एकेडेमीसँग छुट्टै सहमतिमा हुन्छ।'},
si:{a_navAbout:'GKB ගැන',a_navPartnership:'අධ්‍යාපන ආයතන හවුල්කාරිත්වය',a_navPilot:'සති 4 Pilot',a_navMeeting:'හවුල්කාරිත්ව සාකච්ඡාව',a_heroTag:'විදේශීය අධ්‍යාපන ආයතන හවුල්කාරිත්වය',a_hero1:'ඔබේ සිසුන් සූදානම් කරන්න',a_hero2:'කොරියාවේ සැබෑ ජීවිතයට.',a_hero3:'GKB සමඟ හවුල් වන්න.',a_stat2:'Zoom 1:1',a_pilotDesc:'මාර්ගගත Zoom පන්තියේ මූලික ආකෘතිය 1:1 වේ. කණ්ඩායම් හෝ hybrid ආකෘති වෙනම සාකච්ඡා කරයි.'},
id:{a_navAbout:'Tentang GKB',a_navPartnership:'Kemitraan Akademi',a_navPilot:'Pilot 4 Minggu',a_navMeeting:'Diskusi Kemitraan',a_heroTag:'Kemitraan Akademi Luar Negeri',a_hero1:'Persiapkan Siswa Anda',a_hero2:'untuk Kehidupan Nyata di Korea.',a_hero3:'Bermitra dengan GKB.',a_stat2:'Zoom 1:1',a_pilotDesc:'Format online standar adalah Zoom 1:1. Kelas kelompok atau hybrid dibahas terpisah dengan akademi.'},
th:{a_navAbout:'เกี่ยวกับ GKB',a_navPartnership:'ความร่วมมือกับสถาบัน',a_navPilot:'Pilot 4 สัปดาห์',a_navMeeting:'หารือความร่วมมือ',a_heroTag:'ความร่วมมือกับสถาบันต่างประเทศ',a_hero1:'เตรียมนักเรียนของคุณ',a_hero2:'สำหรับชีวิตจริงในเกาหลี',a_hero3:'ร่วมมือกับ GKB',a_stat2:'Zoom 1:1',a_pilotDesc:'รูปแบบออนไลน์มาตรฐานคือ Zoom 1:1 ส่วนชั้นเรียนกลุ่มหรือแบบผสมจะหารือแยกกับสถาบัน'},
km:{a_navAbout:'អំពី GKB',a_navPartnership:'ភាពជាដៃគូសាលា',a_navPilot:'Pilot 4 សប្តាហ៍',a_navMeeting:'ពិភាក្សាភាពជាដៃគូ',a_heroTag:'ភាពជាដៃគូសាលាក្រៅប្រទេស',a_hero1:'ត្រៀមសិស្សរបស់អ្នក',a_hero2:'សម្រាប់ជីវិតពិតនៅកូរ៉េ។',a_hero3:'សហការជាមួយ GKB។',a_stat2:'Zoom 1:1',a_pilotDesc:'ទម្រង់អនឡាញស្តង់ដារគឺ Zoom 1:1។ ថ្នាក់ក្រុម ឬ hybrid នឹងពិភាក្សាដាច់ដោយឡែកជាមួយសាលា។'},
mn:{a_navAbout:'GKB-ийн тухай',a_navPartnership:'Академийн түншлэл',a_navPilot:'4 долоо хоногийн Pilot',a_navMeeting:'Түншлэлийн ярилцлага',a_heroTag:'Гадаад академийн түншлэл',a_hero1:'Суралцагчдаа бэлтгэ',a_hero2:'Солонгосын бодит амьдралд.',a_hero3:'GKB-тэй хамтраарай.',a_stat2:'Zoom 1:1',a_pilotDesc:'Онлайн сургалтын үндсэн хэлбэр нь Zoom 1:1. Бүлгийн болон hybrid хэлбэрийг академитай тусад нь тохирно.'},
ru:{a_navAbout:'О GKB',a_navPartnership:'Партнёрство с академиями',a_navPilot:'4-недельный Pilot',a_navMeeting:'Обсудить партнёрство',a_heroTag:'Партнёрство с зарубежными академиями',a_hero1:'Подготовьте своих учащихся',a_hero2:'к реальной жизни в Корее.',a_hero3:'Сотрудничайте с GKB.',a_stat2:'Zoom 1:1',a_pilotDesc:'Стандартный онлайн-формат — Zoom 1:1. Групповые или гибридные занятия обсуждаются с академией отдельно.'}
};

const GKB_I18N={ko:{...BASE,...KO},en:BASE,vi:{...BASE,...SIMPLE.vi},ne:{...BASE,...SIMPLE.ne},si:{...BASE,...SIMPLE.si},id:{...BASE,...SIMPLE.id},th:{...BASE,...SIMPLE.th},km:{...BASE,...SIMPLE.km},mn:{...BASE,...SIMPLE.mn},ru:{...BASE,...SIMPLE.ru}};

function patchZoomStandard(lang){
 const number=document.querySelector('.statrow .stat:nth-child(2) b');
 if(number) number.textContent='1:1';
 const label=document.querySelector('[data-i18n="a_stat2"]');
 if(label) label.textContent=(lang==='ko'?'Zoom 기본':'Zoom 1:1');
}
function gkbApplyLanguage(lang){
 const p=GKB_I18N[lang]||BASE;
 document.documentElement.lang=lang;
 document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(p[k]!=null)el.textContent=p[k]});
 document.querySelectorAll('[data-i18n-html]').forEach(el=>{const k=el.dataset.i18nHtml;if(p[k]!=null)el.innerHTML=p[k]});
 patchZoomStandard(lang);
 const s=document.getElementById('language');if(s)s.value=lang;
 localStorage.setItem('gkbLanguage',lang);
}
function gkbDetectLanguage(){
 const saved=localStorage.getItem('gkbLanguage');if(saved&&GKB_I18N[saved])return saved;
 const n=(navigator.language||'ko').toLowerCase().split('-')[0];return GKB_I18N[n]?n:'en';
}
document.addEventListener('DOMContentLoaded',()=>{const s=document.getElementById('language');if(s)s.addEventListener('change',e=>gkbApplyLanguage(e.target.value));gkbApplyLanguage(gkbDetectLanguage())});